<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="bom_hoidDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.5.113;Initial Catalog=Database1;Persist Security Info=True;User ID=sa" SettingsObjectName="BOM_SET.Properties.Settings" SettingsPropertyName="Database1_mdfConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Table_BOM_HOLD" Member="Table_BOM_HOLD">
    <Type Name="Table_BOM_HOLD">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="project_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="项目代号" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="项目名称" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="类别" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="设备序号" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="第几次申请" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="密钥" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="备注" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="项目负责人ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="最后修改人ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="是否激活" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="是否提交申请" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="当次审批是否通过" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="是否已获过审批" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="当次计划是否提完" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="是否已提计划" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="当次采购是否完成" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="是否已提采购" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="项目经理" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="项目开始时间" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="项目开始采购时间" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="项目截止采购时间" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="项目调试开始时间" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="项目调试结束时间" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="项目预验收时间" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="项目是否已验收" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="项目终验收时间" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>