#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_SET.sql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1.mdf")]
	public partial class bom_hoidDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertTable_BOM_HOLD(Table_BOM_HOLD instance);
    partial void UpdateTable_BOM_HOLD(Table_BOM_HOLD instance);
    partial void DeleteTable_BOM_HOLD(Table_BOM_HOLD instance);
    #endregion
		
		public bom_hoidDataContext() : 
				base(global::BOM_SET.Properties.Settings.Default.Database1_mdfConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public bom_hoidDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bom_hoidDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bom_hoidDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bom_hoidDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_BOM_HOLD> Table_BOM_HOLD
		{
			get
			{
				return this.GetTable<Table_BOM_HOLD>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_BOM_HOLD")]
	public partial class Table_BOM_HOLD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _project_ID;
		
		private string _项目代号;
		
		private string _项目名称;
		
		private string _类别;
		
		private string _设备序号;
		
		private string _第几次申请;
		
		private string _密钥;
		
		private string _备注;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onproject_IDChanging(int value);
    partial void Onproject_IDChanged();
    partial void On项目代号Changing(string value);
    partial void On项目代号Changed();
    partial void On项目名称Changing(string value);
    partial void On项目名称Changed();
    partial void On类别Changing(string value);
    partial void On类别Changed();
    partial void On设备序号Changing(string value);
    partial void On设备序号Changed();
    partial void On第几次申请Changing(string value);
    partial void On第几次申请Changed();
    partial void On密钥Changing(string value);
    partial void On密钥Changed();
    partial void On备注Changing(string value);
    partial void On备注Changed();
    #endregion
		
		public Table_BOM_HOLD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_project_ID", DbType="Int NOT NULL")]
		public int project_ID
		{
			get
			{
				return this._project_ID;
			}
			set
			{
				if ((this._project_ID != value))
				{
					this.Onproject_IDChanging(value);
					this.SendPropertyChanging();
					this._project_ID = value;
					this.SendPropertyChanged("project_ID");
					this.Onproject_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_项目代号", DbType="NChar(10)")]
		public string 项目代号
		{
			get
			{
				return this._项目代号;
			}
			set
			{
				if ((this._项目代号 != value))
				{
					this.On项目代号Changing(value);
					this.SendPropertyChanging();
					this._项目代号 = value;
					this.SendPropertyChanged("项目代号");
					this.On项目代号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_项目名称", DbType="NChar(10)")]
		public string 项目名称
		{
			get
			{
				return this._项目名称;
			}
			set
			{
				if ((this._项目名称 != value))
				{
					this.On项目名称Changing(value);
					this.SendPropertyChanging();
					this._项目名称 = value;
					this.SendPropertyChanged("项目名称");
					this.On项目名称Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_类别", DbType="NChar(10)")]
		public string 类别
		{
			get
			{
				return this._类别;
			}
			set
			{
				if ((this._类别 != value))
				{
					this.On类别Changing(value);
					this.SendPropertyChanging();
					this._类别 = value;
					this.SendPropertyChanged("类别");
					this.On类别Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_设备序号", DbType="NChar(10)")]
		public string 设备序号
		{
			get
			{
				return this._设备序号;
			}
			set
			{
				if ((this._设备序号 != value))
				{
					this.On设备序号Changing(value);
					this.SendPropertyChanging();
					this._设备序号 = value;
					this.SendPropertyChanged("设备序号");
					this.On设备序号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_第几次申请", DbType="NChar(10)")]
		public string 第几次申请
		{
			get
			{
				return this._第几次申请;
			}
			set
			{
				if ((this._第几次申请 != value))
				{
					this.On第几次申请Changing(value);
					this.SendPropertyChanging();
					this._第几次申请 = value;
					this.SendPropertyChanged("第几次申请");
					this.On第几次申请Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_密钥", DbType="NChar(10)")]
		public string 密钥
		{
			get
			{
				return this._密钥;
			}
			set
			{
				if ((this._密钥 != value))
				{
					this.On密钥Changing(value);
					this.SendPropertyChanging();
					this._密钥 = value;
					this.SendPropertyChanged("密钥");
					this.On密钥Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_备注", DbType="NChar(255)")]
		public string 备注
		{
			get
			{
				return this._备注;
			}
			set
			{
				if ((this._备注 != value))
				{
					this.On备注Changing(value);
					this.SendPropertyChanging();
					this._备注 = value;
					this.SendPropertyChanged("备注");
					this.On备注Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
