#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_SET.sql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1.mdf")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertTable_bom_all(Table_bom_all instance);
    partial void UpdateTable_bom_all(Table_bom_all instance);
    partial void DeleteTable_bom_all(Table_bom_all instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::BOM_SET.Properties.Settings.Default.Database1_mdfConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_bom_all> Table_bom_all
		{
			get
			{
				return this.GetTable<Table_bom_all>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_bom_all")]
	public partial class Table_bom_all : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _代码;
		
		private string _名称;
		
		private string _全名;
		
		private string _规格型号;
		
		private string _审核人;
		
		private string _附件;
		
		private string _图片;
		
		private System.Nullable<int> _价格;
		
		private string _技术参数;
		
		private string _品牌;
		
		private string _备注;
		
		private string _资料路径;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void On代码Changing(string value);
    partial void On代码Changed();
    partial void On名称Changing(string value);
    partial void On名称Changed();
    partial void On全名Changing(string value);
    partial void On全名Changed();
    partial void On规格型号Changing(string value);
    partial void On规格型号Changed();
    partial void On审核人Changing(string value);
    partial void On审核人Changed();
    partial void On附件Changing(string value);
    partial void On附件Changed();
    partial void On图片Changing(string value);
    partial void On图片Changed();
    partial void On价格Changing(System.Nullable<int> value);
    partial void On价格Changed();
    partial void On技术参数Changing(string value);
    partial void On技术参数Changed();
    partial void On品牌Changing(string value);
    partial void On品牌Changed();
    partial void On备注Changing(string value);
    partial void On备注Changed();
    partial void On资料路径Changing(string value);
    partial void On资料路径Changed();
    #endregion
		
		public Table_bom_all()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_代码", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string 代码
		{
			get
			{
				return this._代码;
			}
			set
			{
				if ((this._代码 != value))
				{
					this.On代码Changing(value);
					this.SendPropertyChanging();
					this._代码 = value;
					this.SendPropertyChanged("代码");
					this.On代码Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_名称", DbType="NVarChar(255)")]
		public string 名称
		{
			get
			{
				return this._名称;
			}
			set
			{
				if ((this._名称 != value))
				{
					this.On名称Changing(value);
					this.SendPropertyChanging();
					this._名称 = value;
					this.SendPropertyChanged("名称");
					this.On名称Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_全名", DbType="NVarChar(255)")]
		public string 全名
		{
			get
			{
				return this._全名;
			}
			set
			{
				if ((this._全名 != value))
				{
					this.On全名Changing(value);
					this.SendPropertyChanging();
					this._全名 = value;
					this.SendPropertyChanged("全名");
					this.On全名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_规格型号", DbType="NVarChar(255)")]
		public string 规格型号
		{
			get
			{
				return this._规格型号;
			}
			set
			{
				if ((this._规格型号 != value))
				{
					this.On规格型号Changing(value);
					this.SendPropertyChanging();
					this._规格型号 = value;
					this.SendPropertyChanged("规格型号");
					this.On规格型号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_审核人", DbType="NVarChar(255)")]
		public string 审核人
		{
			get
			{
				return this._审核人;
			}
			set
			{
				if ((this._审核人 != value))
				{
					this.On审核人Changing(value);
					this.SendPropertyChanging();
					this._审核人 = value;
					this.SendPropertyChanged("审核人");
					this.On审核人Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_附件", DbType="NVarChar(255)")]
		public string 附件
		{
			get
			{
				return this._附件;
			}
			set
			{
				if ((this._附件 != value))
				{
					this.On附件Changing(value);
					this.SendPropertyChanging();
					this._附件 = value;
					this.SendPropertyChanged("附件");
					this.On附件Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_图片", DbType="NVarChar(255)")]
		public string 图片
		{
			get
			{
				return this._图片;
			}
			set
			{
				if ((this._图片 != value))
				{
					this.On图片Changing(value);
					this.SendPropertyChanging();
					this._图片 = value;
					this.SendPropertyChanged("图片");
					this.On图片Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_价格", DbType="Int")]
		public System.Nullable<int> 价格
		{
			get
			{
				return this._价格;
			}
			set
			{
				if ((this._价格 != value))
				{
					this.On价格Changing(value);
					this.SendPropertyChanging();
					this._价格 = value;
					this.SendPropertyChanged("价格");
					this.On价格Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_技术参数", DbType="NVarChar(255)")]
		public string 技术参数
		{
			get
			{
				return this._技术参数;
			}
			set
			{
				if ((this._技术参数 != value))
				{
					this.On技术参数Changing(value);
					this.SendPropertyChanging();
					this._技术参数 = value;
					this.SendPropertyChanged("技术参数");
					this.On技术参数Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_品牌", DbType="NVarChar(255)")]
		public string 品牌
		{
			get
			{
				return this._品牌;
			}
			set
			{
				if ((this._品牌 != value))
				{
					this.On品牌Changing(value);
					this.SendPropertyChanging();
					this._品牌 = value;
					this.SendPropertyChanged("品牌");
					this.On品牌Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_备注", DbType="NVarChar(255)")]
		public string 备注
		{
			get
			{
				return this._备注;
			}
			set
			{
				if ((this._备注 != value))
				{
					this.On备注Changing(value);
					this.SendPropertyChanging();
					this._备注 = value;
					this.SendPropertyChanged("备注");
					this.On备注Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_资料路径", DbType="NVarChar(255)")]
		public string 资料路径
		{
			get
			{
				return this._资料路径;
			}
			set
			{
				if ((this._资料路径 != value))
				{
					this.On资料路径Changing(value);
					this.SendPropertyChanging();
					this._资料路径 = value;
					this.SendPropertyChanged("资料路径");
					this.On资料路径Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
