CREATE TABLE [dbo].[Table]
(
	[序号] INT NOT NULL PRIMARY KEY, 
	 [代码] NVARCHAR(255) NULL, 
    [名称] NVARCHAR(255) NULL, 
    [全名] NVARCHAR(255) NULL, 
    [规格型号] NVARCHAR(255) NULL, 
    [审核人] NVARCHAR(255) NULL, 
    [附件] NVARCHAR(255) NULL, 
    [图片] NVARCHAR(255) NULL
)
